// <auto-generated />
using System;
using AlbumCollection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumCollection.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumCollection.Models.Albums", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistID");

                    b.Property<int?>("ArtistsID");

                    b.Property<string>("Recordlabel");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ArtistsID");

                    b.ToTable("Albums");

                    b.HasData(
                        new { ID = 1, ArtistID = 1, Recordlabel = "Wicked Awesome", Title = "Indicud" },
                        new { ID = 2, ArtistID = 2, Recordlabel = "Chrysalis Records", Title = "Sports" },
                        new { ID = 3, ArtistID = 3, Recordlabel = "Dreamville", Title = "2014 Forest Hills Drive" },
                        new { ID = 4, ArtistID = 4, Recordlabel = "Half Awake", Title = "Wandered Away" },
                        new { ID = 5, ArtistID = 5, Recordlabel = "Nitro Records", Title = "Smash" },
                        new { ID = 6, ArtistID = 6, Recordlabel = "Lookout!", Title = "Dookie" },
                        new { ID = 7, ArtistID = 7, Recordlabel = "Island Records", Title = "Joshua Tree" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Artists", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Hometown");

                    b.Property<string>("Name");

                    b.Property<string>("Recordlabel");

                    b.HasKey("ID");

                    b.ToTable("Artists");

                    b.HasData(
                        new { ID = 1, Age = 35, Hometown = "Cleveland, OH", Name = "Kid Cudi", Recordlabel = "Wicked Awesome" },
                        new { ID = 2, Age = 40, Hometown = "San Francisco, CA", Name = "Heuy Lewis And The News", Recordlabel = "Chrysalis Records" },
                        new { ID = 3, Age = 34, Hometown = "Fayetteville, NC", Name = "J. Cole", Recordlabel = "Dreamville" },
                        new { ID = 4, Age = 23, Hometown = "Stockholm, Sweden", Name = "Anna Leone", Recordlabel = "Half Awake" },
                        new { ID = 5, Age = 35, Hometown = "Garden Grove, CA", Name = "The Offspring", Recordlabel = "Nitro Records" },
                        new { ID = 6, Age = 33, Hometown = "Oakland, CA", Name = "Green Day", Recordlabel = "Lookout!" },
                        new { ID = 7, Age = 32, Hometown = "Dublin, Ireland", Name = "U2", Recordlabel = "Island Records" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Songs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumID");

                    b.Property<int?>("AlbumsID");

                    b.Property<string>("Duration");

                    b.Property<string>("Songtitle");

                    b.HasKey("ID");

                    b.HasIndex("AlbumsID");

                    b.ToTable("Songs");

                    b.HasData(
                        new { ID = 1, AlbumID = 1, Duration = "2:40", Songtitle = "the resurrection of scott mescud" },
                        new { ID = 2, AlbumID = 1, Duration = "4:35", Songtitle = "Unfuckwittable" },
                        new { ID = 3, AlbumID = 1, Duration = "3:48", Songtitle = "Just What I Am" },
                        new { ID = 4, AlbumID = 1, Duration = "4:24", Songtitle = "Young Lady" },
                        new { ID = 5, AlbumID = 1, Duration = "4:16", Songtitle = "King Wizard" },
                        new { ID = 6, AlbumID = 1, Duration = "5:01", Songtitle = "Immortal " },
                        new { ID = 7, AlbumID = 1, Duration = "3:34", Songtitle = "Solo Duo, Part II " },
                        new { ID = 8, AlbumID = 1, Duration = "4:27", Songtitle = "Girls" },
                        new { ID = 9, AlbumID = 1, Duration = "1:53", Songtitle = "New York City Rage Fest " },
                        new { ID = 10, AlbumID = 1, Duration = "3:54", Songtitle = "Red Eye " },
                        new { ID = 11, AlbumID = 1, Duration = "4:08", Songtitle = "Mad solar " },
                        new { ID = 12, AlbumID = 1, Duration = "3:13", Songtitle = "Beez" },
                        new { ID = 13, AlbumID = 1, Duration = "4:41", Songtitle = "Brothers" },
                        new { ID = 14, AlbumID = 1, Duration = "2:58", Songtitle = "Burn Baby Burn" },
                        new { ID = 15, AlbumID = 1, Duration = "2:46", Songtitle = "Lord of the Sad and Lonely" },
                        new { ID = 16, AlbumID = 1, Duration = "2:32", Songtitle = "Cold Blooded" },
                        new { ID = 17, AlbumID = 1, Duration = "9:03", Songtitle = "Afterwards (Bring yo Friends)" },
                        new { ID = 18, AlbumID = 1, Duration = "2:51", Songtitle = "The Flight of the Moon Man" },
                        new { ID = 19, AlbumID = 2, Duration = "5:05", Songtitle = "The Heart Of Rock And Roll" },
                        new { ID = 20, AlbumID = 2, Duration = "4:13", Songtitle = "Heart And Soul" },
                        new { ID = 21, AlbumID = 2, Duration = "3:48", Songtitle = "Bad Is Bad" },
                        new { ID = 22, AlbumID = 2, Duration = "4:46", Songtitle = "I Want A New Drug" },
                        new { ID = 23, AlbumID = 2, Duration = "5:11", Songtitle = "Walking On A Thin Line" },
                        new { ID = 24, AlbumID = 2, Duration = "3:53", Songtitle = "Finally Found A Home" },
                        new { ID = 25, AlbumID = 2, Duration = "3:53", Songtitle = "If This Is It" },
                        new { ID = 26, AlbumID = 2, Duration = "3:43", Songtitle = "You Crack Me Up" },
                        new { ID = 27, AlbumID = 2, Duration = "3:21", Songtitle = "Honky Tonk Blues" },
                        new { ID = 28, AlbumID = 3, Duration = "2:09", Songtitle = "Intro" },
                        new { ID = 29, AlbumID = 3, Duration = "4:02", Songtitle = "January 28th" },
                        new { ID = 30, AlbumID = 3, Duration = "3:59", Songtitle = "Wet Dreamz" },
                        new { ID = 31, AlbumID = 3, Duration = "4:24", Songtitle = "03' Adolescence" },
                        new { ID = 32, AlbumID = 3, Duration = "4:29", Songtitle = "A Tale of 2 Citiez" },
                        new { ID = 33, AlbumID = 3, Duration = "4:48", Songtitle = "Fire Squad" },
                        new { ID = 34, AlbumID = 3, Duration = "4:17", Songtitle = "St. Tropez" },
                        new { ID = 35, AlbumID = 3, Duration = "5:01", Songtitle = "G.O.M.D." },
                        new { ID = 36, AlbumID = 3, Duration = "4:52", Songtitle = "No Role Modelz" },
                        new { ID = 37, AlbumID = 3, Duration = "3:39", Songtitle = "Hello" },
                        new { ID = 38, AlbumID = 3, Duration = "4:53", Songtitle = "Apparently" },
                        new { ID = 39, AlbumID = 3, Duration = "3:31", Songtitle = "Love Yourz" },
                        new { ID = 40, AlbumID = 3, Duration = "14:35", Songtitle = "Note to Self" },
                        new { ID = 41, AlbumID = 4, Duration = "4:15", Songtitle = "I Never Really" },
                        new { ID = 42, AlbumID = 4, Duration = "3:59", Songtitle = "My Soul I" },
                        new { ID = 43, AlbumID = 4, Duration = "3:45", Songtitle = "Wandered Away" },
                        new { ID = 44, AlbumID = 4, Duration = "3:05", Songtitle = "If You Only" },
                        new { ID = 45, AlbumID = 4, Duration = "3:48", Songtitle = "Into the Cold" },
                        new { ID = 46, AlbumID = 5, Duration = "0:25", Songtitle = "Time to Relax" },
                        new { ID = 47, AlbumID = 5, Duration = "2:27", Songtitle = "Nitro" },
                        new { ID = 48, AlbumID = 5, Duration = "3:52", Songtitle = "Bad Habit" },
                        new { ID = 49, AlbumID = 5, Duration = "3:52", Songtitle = "Gotta Get Away" },
                        new { ID = 50, AlbumID = 5, Duration = "3:33", Songtitle = "Genocide" },
                        new { ID = 51, AlbumID = 5, Duration = "3:17", Songtitle = "Something to Believe In" },
                        new { ID = 52, AlbumID = 5, Duration = "3:17", Songtitle = "Come Out and Play" },
                        new { ID = 53, AlbumID = 5, Duration = "4:17", Songtitle = "Self Esteem" },
                        new { ID = 54, AlbumID = 5, Duration = "2:43", Songtitle = "It’ll Be a Long Time" },
                        new { ID = 55, AlbumID = 5, Duration = "2:02", Songtitle = "Killboy Powerhead" },
                        new { ID = 56, AlbumID = 5, Duration = "2:12", Songtitle = "What Happened to You?" },
                        new { ID = 57, AlbumID = 5, Duration = "1:17", Songtitle = "So Alone" },
                        new { ID = 58, AlbumID = 5, Duration = "2:54", Songtitle = "Not the One" },
                        new { ID = 59, AlbumID = 5, Duration = "10:42", Songtitle = "Smash" },
                        new { ID = 60, AlbumID = 6, Duration = "2:07", Songtitle = "Burnou" },
                        new { ID = 61, AlbumID = 6, Duration = "2:54", Songtitle = "Having a Blast" },
                        new { ID = 62, AlbumID = 6, Duration = "2:54", Songtitle = "Chump" },
                        new { ID = 63, AlbumID = 6, Duration = "3:59", Songtitle = "Longview" },
                        new { ID = 64, AlbumID = 6, Duration = "3:44", Songtitle = "Welcome to Paradise" },
                        new { ID = 65, AlbumID = 6, Duration = "2:31", Songtitle = "Pulling Teeth" },
                        new { ID = 66, AlbumID = 6, Duration = "3:01", Songtitle = "Basket Case" },
                        new { ID = 67, AlbumID = 6, Duration = "2:14", Songtitle = "She" },
                        new { ID = 68, AlbumID = 6, Duration = "2:37", Songtitle = "Sassafras Roots" },
                        new { ID = 69, AlbumID = 6, Duration = "2:58", Songtitle = "When I Come Around" },
                        new { ID = 70, AlbumID = 6, Duration = "1:34", Songtitle = "Coming Clean" },
                        new { ID = 71, AlbumID = 6, Duration = "1:43", Songtitle = "Emenius Sleepus" },
                        new { ID = 72, AlbumID = 6, Duration = "1:46", Songtitle = "In the End" },
                        new { ID = 73, AlbumID = 6, Duration = "5:46", Songtitle = "F.O.D." },
                        new { ID = 74, AlbumID = 7, Duration = "5:38", Songtitle = "Where The Streets Have No Name" },
                        new { ID = 75, AlbumID = 7, Duration = "4:38", Songtitle = "I Still Haven’t Found What I’m Looking For" },
                        new { ID = 76, AlbumID = 7, Duration = "4:56", Songtitle = "With or Without You" },
                        new { ID = 77, AlbumID = 7, Duration = "4:32", Songtitle = "Bullet the Blue Sky" },
                        new { ID = 78, AlbumID = 7, Duration = "4:18", Songtitle = "Running to Stand STill" },
                        new { ID = 79, AlbumID = 7, Duration = "4:54", Songtitle = "Red Hill Mining Town" },
                        new { ID = 80, AlbumID = 7, Duration = "2:57", Songtitle = "In God’s Country" },
                        new { ID = 81, AlbumID = 7, Duration = "3:33", Songtitle = "Trip Through Your Wires" },
                        new { ID = 82, AlbumID = 7, Duration = "5:23", Songtitle = "One Tree Hill" },
                        new { ID = 83, AlbumID = 7, Duration = "4:13", Songtitle = "Exit" },
                        new { ID = 84, AlbumID = 7, Duration = "5:12", Songtitle = "Mothers of the Disappeared" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Albums", b =>
                {
                    b.HasOne("AlbumCollection.Models.Artists", "Artists")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistsID");
                });

            modelBuilder.Entity("AlbumCollection.Models.Songs", b =>
                {
                    b.HasOne("AlbumCollection.Models.Albums", "Albums")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumsID");
                });
#pragma warning restore 612, 618
        }
    }
}
